language: node_js
sudo: false
node_js:
  - 9
  - 8
  - 6
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - nvm use $TRAVIS_NODE_VERSION
  - npm set loglevel error
  - npm set progress false
